package io.github.zixt233.pirt.runtime

import org.junit.Assert.assertEquals
import org.junit.Test

class PRootRuntimeTest {
    @Test
    fun buildsResolverConfigFromCurrentAndroidDns() {
        assertEquals(
            """
                # Generated by PIRT from the active Android network.
                nameserver 192.168.1.1
                nameserver 2001:db8::53
                nameserver 8.8.8.8
            """.trimIndent() + "\n",
            buildGuestResolvConf(
                listOf(" 192.168.1.1 ", "192.168.1.1", "2001:db8::53", "", "8.8.8.8"),
            ),
        )
    }
}
